name: Demand Capacity Matching

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  match:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Run matching algorithm
      run: python main.py
    
    - name: Upload output CSV
      uses: actions/upload-artifact@v4
      with:
        name: output-csv
        path: output.csv
